// Palette URL: http://paletton.com/#uid=44c1p0kllllkVGyl7sAlze5lL6P */

export const colorPrimary0 = '#120349'; // Main Primary color */
export const colorPrimary1 = '#180365';
export const colorPrimary2 = '#150458';
export const colorPrimary3 = '#0e0337';
export const colorPrimary4 = '#08011f';

export const colorSecondary10 = '#217014'; // Main Secondary color (1) */
export const colorSecondary11 = '#1dd800';
export const colorSecondary12 = '#22a10e';
export const colorSecondary13 = '#22511b';
export const colorSecondary14 = '#152912';

export const colorSecondary20 = '#87191b'; // Main Secondary color (2) */
export const colorSecondary21 = '#fd0006';
export const colorSecondary22 = '#c11116';
export const colorSecondary23 = '#612022';
export const colorSecondary24 = '#311516';

export const colorComplement0 = '#887419'; // Main Complement color */
export const colorComplement1 = '#ffd100';
export const colorComplement2 = '#c3a211';
export const colorComplement3 = '#625620';
export const colorComplement4 = '#312c16';

export const color1 = '#3111a9';

// Generated by Paletton.com © 2002-2014 */
// http://paletton.com */

export const buttonLightenAmount = 0.05;
export const buttonDarkenAmount = 0.15;
export const aLightenAmmount = 0.25;

/* ------------------------------------------------------ */
/* ------------------ COMPONENT COLORS ------------------ */
/* ------------------------------------------------------ */
// NAVBAR
export const navbarBackgroundColor = colorPrimary3;

// TOOLTIP
export const tooltipBackgroundColor = colorPrimary1;
export const tooltipTextColor = '#fff';

// ACCESS CONTROL (LOGIN/REGISTER)
export const accessCtrlBackgroundColor = colorPrimary3;

// NAVBAR
export const alertDetailsBackgroundColor = colorPrimary0;

// DASHBOARD
export const dashboardBackgroundColor = colorPrimary4;
export const dashboardContainerColor = colorPrimary3; // bg for AlertList

// NAVBAR
export const alertCardPriceColor = colorComplement2;

// MESSAGE
export const messageSuccessColor = colorSecondary12;
export const messageErrorColor = colorSecondary22;
export const messageBackgroundColor = colorPrimary4;

// MODAL
export const modalWindowBackgroundColor = colorPrimary3;

/* ---------- BUTTON COLORS ---------- */
export const buttonTextColor = '#fff';
export const buttonDefaultColor = colorPrimary1;

export const buttonNewAlertColor = colorSecondary12;
